server:
  port: 8100

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.wjq.springcloud.api.bean        # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
  application:
    name: springcloud-eureka-6100     #这个就说服务访问的id
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/clouddb01              # 数据库名称
    username: root
    password: 20152154
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200



#整合erueka
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://emp.eureka6100.com:6100/eureka
  instance:
    instance-id: springcloud-eureka-6100
    prefer-ip-address: true     #访问路径可以显示IP地址



info:
  author.name: wjq





