server:
  port: 7100

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://emp.eureka6100.com:6100/eureka/,http://emp.eureka6200.com:6200/eureka/,http://emp.eureka6300.com:6300/eureka/
