server:
  port: 6200

eureka:
  instance:
    hostname: emp.eureka6200.com            #eureka服务端的实例名称
  client:
    register-with-eureka: false         #false表示不向注册中心注册自己。
    fetch-registry: false               #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://emp.eureka6100.com:6100,http://emp.eureka6300.com:6300





